[dt-overlay-at91][PATCH]
linux4sam/dt-overlay-at91 pull request #3
Opened 2020-05-05 15:42 UTC by cybdarren

Added Thermo5 click board support for sama5d27_som1_ek and sam9x60ek

2020-05-06 15:17 UTC, cristibirsan requested changes
Thank you for sending this and congratulations for your first patches !

There are some minor fixes needed before merging. I added them in the review.

Regards,
Cristian

2020-05-06 15:17 UTC, cristibirsan commented on sama5d27_som1_ek.its
> +                        description = "FDY overlay for Thermo5 click";
You have a typo here FDY -> FDT

2020-05-06 15:17 UTC, cristibirsan commented on sama5d27_som1_ek.its
> +
No need for space here

2020-05-06 15:17 UTC, cristibirsan commented on sama5d27_som1_ek/sama5d27_som1_ek_thermo5.dtso
> +/dts-v1/;
Add license information here. We use SPDX-License-Identifier: (GPL-2.0+ OR MIT)

2020-05-06 15:44 UTC, cybdarren commented on sama5d27_som1_ek.its
> +
Space removed to be consistent with other files

2020-05-06 15:44 UTC, cybdarren commented on sama5d27_som1_ek.its
> +                        description = "FDY overlay for Thermo5 click";
Typo corrected

2020-05-06 15:44 UTC, cybdarren commented on sama5d27_som1_ek/sama5d27_som1_ek_thermo5.dtso
> +/dts-v1/;
License headers added to thermo5 clicks

2020-05-06 15:47 UTC, cybdarren commented
Requested changes made…

Cheers,
   Darren


From: Cristian Birsan <notifications@github.com>
Sent: 06 May 2020 16:18
To: linux4sam/dt-overlay-at91 <dt-overlay-at91@noreply.github.com>
Cc: Darren Wenn - M91145 <Darren.Wenn@microchip.com>; Author <author@noreply.github.com>
Subject: Re: [linux4sam/dt-overlay-at91] [dt-overlay-at91][PATCH] (#3)

EXTERNAL EMAIL: Do not click links or open attachments unless you know the content is safe

@cristibirsan requested changes on this pull request.

Thank you for sending this and congratulations for your first patches !

There are some minor fixes needed before merging. I added them in the review.

Regards,
Cristian

________________________________

In sama5d27_som1_ek.its<https://github.com/linux4sam/dt-overlay-at91/pull/3#discussion_r420807349>:

> @@ -178,5 +194,11 @@

                       description = "FDT overlay blob for ov5640 sensor";

                       fdt = "fdt_ov5640";

               };

+

+                thermo5 {

+                        description = "FDY overlay for Thermo5 click";

You have a typo here FDY -> FDT

________________________________

In sama5d27_som1_ek.its<https://github.com/linux4sam/dt-overlay-at91/pull/3#discussion_r420809738>:

> +

+                fdt_thermo5 {

+                        description = "Device Tree blob Thermo5 Click overlay";

+                        data = /incbin/("./sama5d27_som1_ek/sama5d27_som1_ek_thermo5.dtbo");

+                        type = "flat_dt";

+                        arch = "arm";

+                        compression = "none";

+                        load = <0x23190000>;

+                        hash@1 {

+                                algo = "crc32";

+                        };

+                        hash@2 {

+                                algo = "sha1";

+                        };

+                };

+

No need for space here

________________________________

In sama5d27_som1_ek/sama5d27_som1_ek_thermo5.dtso<https://github.com/linux4sam/dt-overlay-at91/pull/3#discussion_r420873006>:

> @@ -0,0 +1,18 @@

+/dts-v1/;

Add license information here. We use SPDX-License-Identifier: (GPL-2.0+ OR MIT)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/linux4sam/dt-overlay-at91/pull/3#pullrequestreview-406633497>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ADU6NMXKH6ANWHVHLT7Q4ETRQF5SXANCNFSM4MZV4KEQ>.

2020-05-07 16:06 UTC, cristibirsan commented
Merged. Thank you,
Cristian

2020-05-07 16:06 UTC, closed without merging